apiVersion: v1
kind: Pod
metadata:
  name: dof-exam-pod-1
  labels:
    app: dof-exam-1

spec:
    containers:
    - name: nginx-host
      image: iatanasov77/dof-exam-nginx:1.0

      ports:
      - containerPort: 80
      volumeMounts:
      - name: nginx-site
        mountPath: /site
        
    - name: php-host
      image: iatanasov77/dof-exam-php:1.0

      ports:
      - containerPort: 9000
      volumeMounts:
      - mountPath: /site
        name: php-site
        
    - name: redis-host
      image: redis:latest
      resources: {}
      
    restartPolicy: Always

    volumes:
    - name: nginx-site
      hostPath:
        path: /opt/jenkins_slave/workspace/RetakeExam-Application/app
        type: Directory
    - name: php-site
      hostPath:
        path: /opt/jenkins_slave/workspace/RetakeExam-Application/app
        type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: dof-exam-svc-1
  labels:
    app: dof-exam-1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
    name: nginx-host
  selector:
    app: dof-exam-1
---
apiVersion: v1
kind: Service
metadata:
  name: php-host
  labels:
    app: dof-exam-1
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    app: dof-exam-1
---
apiVersion: v1
kind: Service
metadata:
  name: redis-host
  labels:
    app: dof-exam-1
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: dof-exam-1
